spring.config.import=optional:file:.env[.properties]
spring.application.name=uteshop-example-2
server.port=${PORT:8081}
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/vidu2;AUTO_SERVER=TRUE}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
server.servlet.session.timeout=60m
server.error.include-message=never
app.demo.seed=${DEMO_SEED:true}

spring.profiles.default=sqlserver
